// Voice configuration data for TTS
window.voices = [
  // TikTok TTS Voices
  { id: 'en_us_001', name: 'TikTok US English (F1)', language: 'en-US', gender: 'female', provider: 'tiktok' },
  { id: 'en_us_002', name: 'TikTok US English (F2)', language: 'en-US', gender: 'female', provider: 'tiktok' },
  { id: 'en_us_006', name: 'TikTok US English (M1)', language: 'en-US', gender: 'male', provider: 'tiktok' },
  { id: 'en_us_007', name: 'TikTok US English (M2)', language: 'en-US', gender: 'male', provider: 'tiktok' },
  { id: 'en_us_009', name: 'TikTok US English (M3)', language: 'en-US', gender: 'male', provider: 'tiktok' },
  { id: 'en_us_010', name: 'TikTok US English (M4)', language: 'en-US', gender: 'male', provider: 'tiktok' },
  { id: 'en_uk_001', name: 'TikTok UK English (M1)', language: 'en-GB', gender: 'male', provider: 'tiktok' },
  { id: 'en_uk_003', name: 'TikTok UK English (M2)', language: 'en-GB', gender: 'male', provider: 'tiktok' },
  { id: 'en_au_001', name: 'TikTok Australian English (F)', language: 'en-AU', gender: 'female', provider: 'tiktok' },
  { id: 'en_au_002', name: 'TikTok Australian English (M)', language: 'en-AU', gender: 'male', provider: 'tiktok' },
  { id: 'fr_001', name: 'TikTok French (M1)', language: 'fr-FR', gender: 'male', provider: 'tiktok' },
  { id: 'fr_002', name: 'TikTok French (M2)', language: 'fr-FR', gender: 'male', provider: 'tiktok' },
  { id: 'de_001', name: 'TikTok German (F)', language: 'de-DE', gender: 'female', provider: 'tiktok' },
  { id: 'de_002', name: 'TikTok German (M)', language: 'de-DE', gender: 'male', provider: 'tiktok' },
  { id: 'es_002', name: 'TikTok Spanish ES (M)', language: 'es-ES', gender: 'male', provider: 'tiktok' },
  { id: 'es_mx_002', name: 'TikTok Spanish MX (M)', language: 'es-MX', gender: 'male', provider: 'tiktok' },
  { id: 'br_001', name: 'TikTok Portuguese BR (F1)', language: 'pt-BR', gender: 'female', provider: 'tiktok' },
  { id: 'br_003', name: 'TikTok Portuguese BR (F2)', language: 'pt-BR', gender: 'female', provider: 'tiktok' },
  { id: 'br_004', name: 'TikTok Portuguese BR (F3)', language: 'pt-BR', gender: 'female', provider: 'tiktok' },
  { id: 'br_005', name: 'TikTok Portuguese BR (M)', language: 'pt-BR', gender: 'male', provider: 'tiktok' },
  { id: 'jp_001', name: 'TikTok Japanese (F1)', language: 'ja-JP', gender: 'female', provider: 'tiktok' },
  { id: 'jp_003', name: 'TikTok Japanese (F2)', language: 'ja-JP', gender: 'female', provider: 'tiktok' },
  { id: 'jp_005', name: 'TikTok Japanese (F3)', language: 'ja-JP', gender: 'female', provider: 'tiktok' },
  { id: 'jp_006', name: 'TikTok Japanese (M)', language: 'ja-JP', gender: 'male', provider: 'tiktok' },
  { id: 'kr_002', name: 'TikTok Korean (M1)', language: 'ko-KR', gender: 'male', provider: 'tiktok' },
  { id: 'kr_003', name: 'TikTok Korean (F)', language: 'ko-KR', gender: 'female', provider: 'tiktok' },
  { id: 'kr_004', name: 'TikTok Korean (M2)', language: 'ko-KR', gender: 'male', provider: 'tiktok' },
  { id: 'id_001', name: 'TikTok Indonesian (F)', language: 'id-ID', gender: 'female', provider: 'tiktok' },
  { id: 'en_us_ghostface', name: 'TikTok Ghost Face', language: 'en-US', gender: 'male', provider: 'tiktok' },
  { id: 'en_us_c3po', name: 'TikTok C3PO', language: 'en-US', gender: 'male', provider: 'tiktok' },
  { id: 'en_us_stitch', name: 'TikTok Stitch', language: 'en-US', gender: 'male', provider: 'tiktok' },
  { id: 'en_male_pirate', name: 'TikTok Pirate', language: 'en-US', gender: 'male', provider: 'tiktok' },
  { id: 'en_male_narration', name: 'TikTok Narrator', language: 'en-US', gender: 'male', provider: 'tiktok' },
  { id: 'en_female_f08_warmy_breeze', name: 'TikTok Warmy Breeze', language: 'en-US', gender: 'female', provider: 'tiktok' },

  // Browser SpeechSynthesis Voices (built-in, no rate limits)
  { id: 'browser-female', name: 'Browser Voice (Female)', language: 'en-US', gender: 'female', provider: 'browser' },
  { id: 'browser-male', name: 'Browser Voice (Male)', language: 'en-US', gender: 'male', provider: 'browser' },

  // Kokoro TTS Voices (Local ONNX)
  { id: 'af_heart', name: 'Kokoro: Heart (Female)', language: 'en-US', gender: 'female', provider: 'kokoro' },
  { id: 'af_bella', name: 'Kokoro: Bella (Female)', language: 'en-US', gender: 'female', provider: 'kokoro' },
  { id: 'af_nicole', name: 'Kokoro: Nicole (Female)', language: 'en-US', gender: 'female', provider: 'kokoro' },
  { id: 'af_sarah', name: 'Kokoro: Sarah (Female)', language: 'en-US', gender: 'female', provider: 'kokoro' },
  { id: 'af_sky', name: 'Kokoro: Sky (Female)', language: 'en-US', gender: 'female', provider: 'kokoro' },
  { id: 'am_adam', name: 'Kokoro: Adam (Male)', language: 'en-US', gender: 'male', provider: 'kokoro' },
  { id: 'am_michael', name: 'Kokoro: Michael (Male)', language: 'en-US', gender: 'male', provider: 'kokoro' },
  { id: 'bf_alice', name: 'Kokoro: Alice (Female, UK)', language: 'en-GB', gender: 'female', provider: 'kokoro' },
  { id: 'bf_emma', name: 'Kokoro: Emma (Female, UK)', language: 'en-GB', gender: 'female', provider: 'kokoro' },
  { id: 'bm_george', name: 'Kokoro: George (Male, UK)', language: 'en-GB', gender: 'male', provider: 'kokoro' },
  { id: 'bm_lewis', name: 'Kokoro: Lewis (Male, UK)', language: 'en-GB', gender: 'male', provider: 'kokoro' }
];

// Map languages to a proxy base language whose voices they should inherit
window.voiceLanguageOverrides = {
  ace: 'tl', ban: 'tl', btx: 'tl', bts: 'tl', bbc: 'tl', bew: 'tl',
  jv: 'tl', mak: 'tl', 'ms-MS': 'tl', 'ms-Arab': 'tl', min: 'tl', su: 'tl',
  'id-ID': 'tl',
  bik: 'tl', ceb: 'tl', hil: 'tl', ilo: 'tl', pam: 'tl', pag: 'tl',
  fj: 'tl', sm: 'tl', mi: 'tl', haw: 'tl', tet: 'tl', mg: 'tl',
  uk: 'ru', be: 'ru',
  bg: 'ru', mk: 'ru', sr: 'ru', bs: 'ru', hr: 'ru', sl: 'ru',
  ab: 'ru', ba: 'ru', bua: 'ru', cv: 'ru', crh: 'ru',
  kk: 'ru', ky: 'ru', tt: 'ru', tk: 'ru', uz: 'ru', az: 'ru', tr: 'ru',
  mn: 'ru', chm: 'ru', tg: 'ru', ka: 'ru', hy: 'ru',
  yue: 'zh', my: 'zh', lo: 'zh', th: 'zh', km: 'zh', vi: 'zh', dz: 'zh',
  bn: 'hi', as: 'hi', gu: 'hi', mr: 'hi', pa: 'hi', 'pa-Arab': 'hi',
  ne: 'hi', or: 'hi', sa: 'hi', bho: 'hi', mai: 'hi', awa: 'hi',
  doi: 'hi', gom: 'hi', sd: 'hi', ur: 'hi', 'new': 'hi', si: 'hi', dv: 'hi',
  ta: 'hi', te: 'hi', kn: 'hi', ml: 'hi',
  'mni-Mtei': 'hi', lus: 'hi', cnh: 'hi', shn: 'hi',
  ca: 'gl', gl: 'es', qu: 'es', ay: 'es', gn: 'es', yua: 'es',
  pap: 'es', ht: 'fr', scn: 'it', lij: 'it', lmo: 'it', co: 'it',
  oc: 'fr', br: 'fr', 'fr-CA': 'fr', ro: 'it', pt: 'pt', la: 'it',
  nl: 'de', af: 'de', fy: 'de', lb: 'de', li: 'de', hrx: 'de', yi: 'de',
  da: 'en', sv: 'en', no: 'en', is: 'en',
  ga: 'en', gd: 'en', cy: 'en',
  fi: 'en', et: 'en', hu: 'en', lv: 'en', lt: 'en', ltg: 'en', eo: 'en',
  pl: 'de', cs: 'de', sk: 'de', szl: 'de',
  ar: 'en', he: 'en', am: 'en', ti: 'en', om: 'en', so: 'en', ha: 'en', mt: 'en',
  sw: 'en', zu: 'en', xh: 'en', sn: 'en', rw: 'en', rn: 'en',
  lg: 'en', ny: 'en', ts: 'en', tn: 'en', st: 'en', ss: 'en', nr: 'en',
  bem: 'en', cgg: 'en', luo: 'en', nso: 'en', ktu: 'en',
  bm: 'ff', ff: 'fr', ln: 'fr', sg: 'fr',
  yo: 'en', ig: 'en', ee: 'en', ak: 'en', gaa: 'en', kri: 'en',
  din: 'en', nus: 'en', ach: 'en', alz: 'en', crs: 'fr', dov: 'en',
  fa: 'en', ps: 'en', ku: 'en', ckb: 'en',
  'ko-KR': 'ja',
  ug: 'ru', hmn: 'zh', el: 'it', rom: 'ru', eu: 'es', sq: 'it'
};