// Interface UI strings in multiple languages
window.UI_STRINGS = {
  'en-US': {
    // Settings Panel
    personaSettingsTitle: '🧠 Persona System Prompt',
    corePersonaLabel: '🆔 Core Identity',
    corePersonaPlaceholder: 'Describe who you are fundamentally...',
    personaSystemPromptLabel: '🎭 Custom Personality / Roleplay',
    personaPromptPlaceholder: 'e.g., You are a tsundere childhood friend who secretly has a crush on the user. You use biting remarks but care deeply about their well-being...',
    savePersonaBtn: 'Save Persona Settings',
    resetPersonaBtn: 'Reset Persona',
    summaryTriggerCountLabel: '⏲️ Summary Trigger (Every N messages)',
    summaryLengthLabel: '📏 Summary Target Length',
    summaryLenUltraConcise: 'Ultra-Concise (1 sentence)',
    summaryLenConcise: 'Concise (Short paragraph)',
    summaryLenDetailed: 'Detailed (1-2 paragraphs)',
    summaryLenComprehensive: 'Comprehensive (In-depth)',
    conversationSummaryLabel: '📝 Conversation Summary',
    conversationSummaryPlaceholder: 'The AI will automatically update this periodically, but you can edit it here...',
    manualSummarizeBtn: 'Update Summary from Chat',
    summaryCutoffMarker: '--- Summary Boundary (Active Memory Below) ---',

    contextSettingsTitle: '🧠 Context Settings',
    useJsonForEmotionLabel: '📝 Use JSON Format for Emotion (Advanced)',
    useJsonForEmotionDesc: 'Forces the AI to respond in JSON for emotional reactions, but may cause errors on weaker LLMs.',

    memorySettingsTitle: '🧠 Memory Settings',
    conversationMemoryLabel: '🧵 Conversation Memory Size',
    memorySizeCurrent: 'Current:',
    messages: 'messages',
    memoryContextLabel: '📌 Conversation Context',
    memoryContextDesc: 'This text is sent with every request so the AI remembers your long-term background, preferences, or roleplay setup.',
    
    modelSettingsTitle: '🧩 Model Settings',
    selectModelLabel: '🎭 Select Model',
    addCustomModelLabel: '➕ Add Custom Model',
    modelNamePlaceholder: 'Model name (optional)',
    modelUrlPlaceholder: 'Model .model3.json URL',
    modelImagePlaceholder: 'Thumbnail image URL (optional)',
    addModelBtn: 'Add Model',
    customModelsLabel: '📂 Custom Models',
    selectCustomModelPlaceholder: 'Select a custom model',
    resetModelPositionBtn: '♻️ Reset Model Position & Zoom',
    clearAllModelsBtn: '🗑️ Clear All Models',
    openModelGalleryBtn: 'Open Model Gallery',
    clearCustomModelsBtn: '🗑️ Clear Custom Models',
    
    languageSettingsTitle: '🌐 Language Settings',
    responseLanguageLabel: '🈶 Response Language',
    translateToLabel: '🔁 Translate Response To',
    translateNone: 'None',
    showTransliterationLabel: '🔤 Show Transliteration (for JA, KO)',
    translateUILabel: '🈯 Translate User Interface (AI)',
    
    voiceSettingsTitle: '🔊 Voice Settings',
    enableVoiceLabel: '🔈 Enable Voice (TTS)',
    voiceLabel: '🎙️ Voice',
    ttsChunkLimitLabel: '📏 TTS Chunk Character Limit',
    ttsChunkLimitCurrent: 'Max Characters:',
    ttsVolumeLabel: '🔉 TTS Voice Volume',
    ttsVolumeCurrent: 'Volume:',
    enableTikTokVoiceLabel: '🔈 Enable TikTok TTS',
    enableTikTokVoiceDesc: 'Primary voice synthesis using TikTok\'s free TTS API.',
    enableKokoroVoiceLabel: '🚀 Enable Local Voice (Kokoro)',
    kokoroVoiceLabel: '🚀 Kokoro Voice',
    kokoroVoiceDesc: 'High-quality local TTS. Preloaded in background for silent handoff.',
    
    audioSettingsTitle: '🎧 Audio Settings',
    radioStreamLabel: '📻 Radio Stream',
    
    displaySettingsTitle: '🖥️ Display Settings',
    showClockLabel: '⏰ Show Clock',
    chatboxOpacityLabel: '🪟 Chatbox Opacity',
    chatboxOpacityCurrent: 'Current:',
    messageOpacityLabel: '💬 Message Bubble Opacity',
    messageOpacityCurrent: 'Current:',
    bgOpacityLabel: '🖼️ Background Image Opacity',
    
    backgroundSettingsTitle: '🖼️ Background Image',
    bgUrlLabel: '🌐 Custom Background URL',
    bgUrlPlaceholder: 'https://example.com/image.jpg',
    applyBgUrlBtn: 'Set Background',
    clearBgBtn: '🧹 Clear Background',
    bgLibraryLabel: '📚 Background Library',
    openBgViewerBtn: 'Open Fullscreen Viewer',
    toggleBgSelectBtn: 'Select',
    deleteBgSelectedBtn: 'Delete Selected',
    clearBgLibraryBtn: 'Clear Library',

    bgFitLabel: '📐 Background Fit',
    bgFitContain: 'Contain',
    bgFitCover: 'Cover',
    bgFitStretch: 'Stretch',
    bgFitCoverTop: 'Cover • Top',
    bgFitCoverCenter: 'Cover • Center',
    bgFitCoverBottom: 'Cover • Bottom',
    bgFitContainTop: 'Contain • Top',
    bgFitContainCenter: 'Contain • Center',
    bgFitContainBottom: 'Contain • Bottom',
    bgFitFitWidth: 'Fit Width',
    bgFitFitHeight: 'Fit Height',
    
    preferencesTitle: '⚙️ Preferences',
    alwaysShowSettingsLabel: '🪄 Always show Settings on page load',
    alwaysShowSettingsDesc: 'If enabled, the settings panel opens on every load. Otherwise, it remembers your last open/closed state.',
    includeTimeLabel: '⏱️ Include current time in context',
    includeTimeDesc: 'Provides the AI with the current date and time for context-aware responses.',
    includeBatteryLabel: '🔋 Include battery status in context',
    includeBatteryDesc: 'Allows the AI to know your device\'s battery level and charging state.',
    multipleModelsLabel: '🧬 Load multiple models at once',
    multipleModelsDesc: 'When enabled, selecting a model adds it without removing existing ones.',
    
    interfaceLanguageLabel: '🌍 Interface Language',
    
    debugSettingsTitle: '🐞 Debug Settings',
    enableDebuggerLabel: '🧰 Enable Debug Panel',
    showVerboseLogsLabel: '💬 Show Live2d Debug Logs',
    showAIDebugLogsLabel: '🧠 Show AI Debug Logs',
    showTTSDebugLogsLabel: '🔊 Show TTS Debug Logs',
    offlineModeLabel: '🔌 Offline Mode',
    offlineDurationLabel: '⏱️ Offline Duration (seconds)',
    showChatContextLabel: '📄 Show Chat Context in Debug',
    includeTutorialLabel: '📖 Include Tutorial in AI Context',
    searchSettingsPlaceholder: 'Search settings...',
    disableAutoOfflineLabel: '🚫 Disable automatic Offline Mode',
    disableAutoOfflineDesc: 'When enabled, the app will never switch itself into Offline Mode automatically after connection errors.',
    
    helpTutorialTitle: '❓ Help & Tutorial',
    llmSettingsTitle: '🤖 LLM Provider',
    useOpenRouterLabel: 'Use OpenRouter',
    useOpenRouterDesc: 'When enabled, chat, translation, and summarization will call OpenRouter using your API key and model name.',
    openRouterApiKeyLabel: '🔑 OpenRouter API Key',
    openRouterApiKeyDesc: 'Stored locally in your browser and sent only to openrouter.ai over HTTPS.',
    openRouterSectionTitle: 'OpenRouter',
    openRouterPrimaryEnabledLabel: 'Enable primary model',
    openRouterModelLabel: '🧬 OpenRouter Model Name',
    openRouterModelDesc: 'Examples: stepfun/step-3.5-flash:free, nvidia/nemotron-3-super-120b-a12b:free, qwen/qwen3.6-plus-preview:free, etc.',
    openRouterFallbackModel1EnabledLabel: 'Enable fallback model 1',
    openRouterFallbackModel1Label: '🔄 Fallback Model 1',
    openRouterFallbackModel1Desc: 'First fallback model. Used if the primary model fails.',
    openRouterFallbackModel2EnabledLabel: 'Enable fallback model 2',
    openRouterFallbackModel2Label: '🔄 Fallback Model 2',
    openRouterFallbackModel2Desc: 'Second fallback model. Used if the primary and first fallback models fail.',
    groqSectionTitle: 'Groq',
    useGroqLabel: 'Use Groq',
    useGroqDesc: 'When enabled, chat, translation, and summarization will call Groq using your API key and model name.',
    groqApiKeyLabel: '🔑 Groq API Key',
    groqApiKeyDesc: 'Get your free API key from console.groq.com. Stored locally in your browser.',
    groqModelLabel: '🧬 Groq Model Name',
    groqModelDesc: 'Examples: llama-3.3-70b-versatile, llama-3.1-70b-versatile, mixtral-8x7b-32768, etc.',
    openAICompatibleSectionTitle: 'OpenAI Compatible',
    launchTutorialBtn: '📘 Launch Tutorial',
    resetLanguagesBtn: 'Reset Languages',
    playTTSBtn: 'Play TTS',
    pauseTTSBtn: 'Pause TTS',
    stopTTSBtn: 'Stop TTS',
    
    automationSettingsTitle: '🤖 Automation Settings',
    enableUserMessageQueueLabel: '📬 User Message Queue',
    enableUserMessageQueueDesc: 'Queue messages instead of sending immediately while the AI is responding.',
    enableAmbientQueueLabel: '🍃 Ambient Mode',
    enableAmbientQueueDesc: 'The AI will share thoughts or follow-up questions unprompted after periods of silence.',
    ambientPromptLabel: '💭 Ambient Prompt',
    ambientPromptPlaceholder: 'Instructions for Haru\'s unprompted thoughts...',
    ambientDelayLabel: '⏱️ Ambient Trigger Delay (seconds)',
    ambientPreloadLabel: '⚡ Ambient Preload',
    ambientPreloadDesc: 'Pre-fetch the next ambient comment in the background for instant response.',
    clearQueueBtn: '🧹 Clear Message Queue',
    clearQueueChatBtn: 'Clear Queue',
    
    // Chat interface
    messageInputPlaceholder: 'Type your message...',
    sendBtn: 'Send',
    resetChatBtn: 'Reset Chat',
    
    // Tutorial
    appGuideTitle: 'App Guide',
    
    // Common
    noCustomModelsAdded: 'No custom models added'
  }
};

// Helper function to get translated string
window.getString = function(key, lang = 'en-US') {
  const langStrings = window.UI_STRINGS[lang] || window.UI_STRINGS['en-US'];
  return langStrings[key] || key;
};
